// constants/service.js
export const services = [
  // ================= ELECTRICITY (all DisCos) =================
  // image: null → tile renders a colored monogram until you add a logo.
  // To add a logo later: image: require("../../assets/services/discos/ikeja.png")

  {
    id: 13,
    label: "Ikeja Electric",
    category: "electricity",
    screen: "Electricity",
    image: null,
    short: "IE",
    color: "#4B4B4B",
    biller: "ikeja-electric",
  },
  {
    id: 14,
    label: "Eko Electric",
    category: "electricity",
    screen: "Electricity",
    image: null,
    short: "EKO",
    color: "#3F3F3F",
    biller: "eko-electric",
  },
  {
    id: 15,
    label: "Abuja Electric",
    category: "electricity",
    screen: "Electricity",
    image: null,
    short: "AE",
    color: "#5E5E5E",
    biller: "abuja-electric",
  },
  {
    id: 16,
    label: "Ibadan Electric",
    category: "electricity",
    screen: "Electricity",
    image: null,
    short: "IB",
    color: "#A0A0A0",
    biller: "ibadan-electric",
  },
  {
    id: 17,
    label: "Enugu Electric",
    category: "electricity",
    screen: "Electricity",
    image: null,
    short: "EN",
    color: "#3C3C3C",
    biller: "enugu-electric",
  },
  {
    id: 18,
    label: "PH Electric",
    category: "electricity",
    screen: "Electricity",
    image: null,
    short: "PH",
    color: "#595959",
    biller: "portharcourt-electric",
  },
  {
    id: 19,
    label: "Kano Electric",
    category: "electricity",
    screen: "Electricity",
    image: null,
    short: "KN",
    color: "#5B5B5B",
    biller: "kano-electric",
  },
  {
    id: 20,
    label: "Kaduna Electric",
    category: "electricity",
    screen: "Electricity",
    image: null,
    short: "KD",
    color: "#464646",
    biller: "kaduna-electric",
  },
  {
    id: 21,
    label: "Jos Electric",
    category: "electricity",
    screen: "Electricity",
    image: null,
    short: "JOS",
    color: "#686868",
    biller: "jos-electric",
  },
  {
    id: 22,
    label: "Benin Electric",
    category: "electricity",
    screen: "Electricity",
    image: null,
    short: "BN",
    color: "#4A4A4A",
    biller: "benin-electric",
  },
  {
    id: 23,
    label: "Yola Electric",
    category: "electricity",
    screen: "Electricity",
    image: null,
    short: "YL",
    color: "#353535",
    biller: "yola-electric",
  },

  // ================= AIRTIME =================
  {
    id: 1,
    label: "MTN",
    category: "airtime",
    screen: "Airtime",
    serviceType: "airtime",
    network: "mtn",
    image: require("../../assets/services/mtn.png"),
  },
  {
    id: 2,
    label: "Airtel",
    category: "airtime",
    screen: "Airtime",
    serviceType: "airtime",
    network: "airtel",
    image: require("../../assets/services/airtel.png"),
  },
  {
    id: 3,
    label: "Glo",
    category: "airtime",
    screen: "Airtime",
    serviceType: "airtime",
    network: "glo",
    image: require("../../assets/services/glo.png"),
  },
  {
    id: 4,
    label: "9mobile",
    category: "airtime",
    screen: "Airtime",
    serviceType: "airtime",
    network: "9mobile",
    image: require("../../assets/services/9mobile.png"),
  },

  // ================= DATA =================
  {
    id: 5,
    label: "MTN Data",
    category: "data",
    screen: "Airtime",
    serviceType: "data",
    network: "mtn",
    image: require("../../assets/services/mtn.png"),
  },
  {
    id: 6,
    label: "Airtel Data",
    category: "data",
    screen: "Airtime",
    serviceType: "data",
    network: "airtel",
    image: require("../../assets/services/airtel.png"),
  },
  {
    id: 7,
    label: "Glo Data",
    category: "data",
    screen: "Airtime",
    serviceType: "data",
    network: "glo",
    image: require("../../assets/services/glo.png"),
  },
  {
    id: 8,
    label: "9mobile Data",
    category: "data",
    screen: "Airtime",
    serviceType: "data",
    network: "9mobile",
    image: require("../../assets/services/9mobile.png"),
  },

  // ================= CABLE TV =================
  {
    id: 9,
    label: "DSTV",
    category: "tv",
    screen: "TV",
    image: require("../../assets/services/dstv.png"),
  },
  {
    id: 10,
    label: "GOTV",
    category: "tv",
    screen: "TV",
    image: require("../../assets/service2/gotv.png"),
  },
  {
    id: 11,
    label: "StarTimes",
    category: "tv",
    screen: "TV",
    image: require("../../assets/service2/startime.png"),
  },
  {
    id: 12,
    label: "Showmax",
    category: "tv",
    screen: "TV",
    image: require("../../assets/service2/showmax.png"),
  },

  // ================= EDUCATION =================
  {
    id: 24,
    label: "WAEC",
    category: "education",
    screen: "Education",
    image: require("../../assets/service2/waec.png"),
  },
  {
    id: 25,
    label: "JAMB",
    category: "education",
    screen: "Education",
    image: require("../../assets/services/jamb.png"),
  },
];
